#pragma once

#define MASTER_RIGHT

#define DYNAMIC_KEYMAP_LAYER_COUNT 16

#define SPLIT_POINTING_ENABLE
#define SPLIT_LED_STATE_ENABLE
#define SPLIT_TRANSPORT_MIRROR
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_OLED_ENABLE
