#pragma once

#define MASTER_RIGHT

#define DYNAMIC_KEYMAP_LAYER_COUNT 8

#define PERMISSIVE_HOLD

#define SPLIT_POINTING_ENABLE
#define SPLIT_LED_STATE_ENABLE
#define SPLIT_TRANSPORT_MIRROR
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_OLED_ENABLE
#define RGB_DISABLE_WHEN_USB_SUSPENDED
#define RGB_MATRIX_SLEEP
